config:
  # Configuration of email notification
  notify:
    email:


  # Configure local folder for sql and temporary data store for notification
  localfs:
    xls_path: "/"
    sql_path: "/"

  #Secret manager details to fetch postgres creds
  secrets:
    secret_name: ""
    secret_region: ""

  #Postgres connection details to execute the select queries
  postgresJDBC:
    jdbcUrl: ""
    jdbcDatabase: ""
    jdbcSchema: ""
    postgres_user: ""
    postgres_pwd: ""